/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import recursos.ImagenFondo;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 * @author Grupo10 TP6 Altamirano Karina Gianfranco Antonacci Matías Bequis
 * Marcos Ezequiel Dave Natalia Quiroga Dorzan Alejo Franzinni Tatiana
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Escritorio = new recursos.ImagenFondo();
        barra_menu = new javax.swing.JMenuBar();
        jm_archivos = new javax.swing.JMenu();
        jm_alumnos = new javax.swing.JMenu();
        jmi_gestion_alumno = new javax.swing.JMenuItem();
        jm_materias = new javax.swing.JMenu();
        jmi_gestion_materias = new javax.swing.JMenuItem();
        jm_inscripcion = new javax.swing.JMenu();
        jmi_gestion_inscripcion = new javax.swing.JMenuItem();
        jmi_listar_inscripciones = new javax.swing.JMenuItem();
        jm_notas = new javax.swing.JMenu();
        jmi_gestion_notas = new javax.swing.JMenuItem();
        jm_busquedas = new javax.swing.JMenu();
        jmi_filtro_alumnoMateria = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grupo 10 Universidad");

        Escritorio.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        jm_archivos.setText("Archivos");
        barra_menu.add(jm_archivos);

        jm_alumnos.setText("Alumnos");

        jmi_gestion_alumno.setText("Gestión alumnos...");
        jmi_gestion_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_alumnoActionPerformed(evt);
            }
        });
        jm_alumnos.add(jmi_gestion_alumno);

        barra_menu.add(jm_alumnos);

        jm_materias.setText("Materias");

        jmi_gestion_materias.setText("Gestión materias...");
        jmi_gestion_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_materiasActionPerformed(evt);
            }
        });
        jm_materias.add(jmi_gestion_materias);

        barra_menu.add(jm_materias);

        jm_inscripcion.setText("Inscipción");

        jmi_gestion_inscripcion.setText("Gestión inscripción...");
        jmi_gestion_inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_inscripcionActionPerformed(evt);
            }
        });
        jm_inscripcion.add(jmi_gestion_inscripcion);

        jmi_listar_inscripciones.setText("Listar Inscripciones");
        jmi_listar_inscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listar_inscripcionesActionPerformed(evt);
            }
        });
        jm_inscripcion.add(jmi_listar_inscripciones);

        barra_menu.add(jm_inscripcion);

        jm_notas.setText("Notas");

        jmi_gestion_notas.setText("Gestión notas...");
        jmi_gestion_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_notasActionPerformed(evt);
            }
        });
        jm_notas.add(jmi_gestion_notas);

        barra_menu.add(jm_notas);

        jm_busquedas.setText("Búsquedas");

        jmi_filtro_alumnoMateria.setText("Filtro Alumno/Materias");
        jm_busquedas.add(jmi_filtro_alumnoMateria);

        barra_menu.add(jm_busquedas);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //-------------------- Ventana Gestion Alumno --------------------
    private void jmi_gestion_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_alumnoActionPerformed
        // TODO add your handling code here:
        VistaGestionAlumno ventana = new VistaGestionAlumno();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmi_gestion_alumnoActionPerformed

    private void jmi_gestion_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_materiasActionPerformed
        // TODO add your handling code here:
        VistaGestionMaterias ventana = new VistaGestionMaterias();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmi_gestion_materiasActionPerformed

    private void jmi_gestion_inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_inscripcionActionPerformed
        // TODO add your handling code here:
        VistaGestionInscripcion ventana = new VistaGestionInscripcion();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jmi_gestion_inscripcionActionPerformed

    private void jmi_gestion_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_notasActionPerformed
        // TODO add your handling code here:
        VistaGestionNotas ventana = new VistaGestionNotas();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmi_gestion_notasActionPerformed

    private void jmi_listar_inscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listar_inscripcionesActionPerformed
        // TODO add your handling code here:
        VistaListarInscripciones ventana = new VistaListarInscripciones();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
      
    }//GEN-LAST:event_jmi_listar_inscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jm_alumnos;
    private javax.swing.JMenu jm_archivos;
    private javax.swing.JMenu jm_busquedas;
    private javax.swing.JMenu jm_inscripcion;
    private javax.swing.JMenu jm_materias;
    private javax.swing.JMenu jm_notas;
    private javax.swing.JMenuItem jmi_filtro_alumnoMateria;
    private javax.swing.JMenuItem jmi_gestion_alumno;
    private javax.swing.JMenuItem jmi_gestion_inscripcion;
    private javax.swing.JMenuItem jmi_gestion_materias;
    private javax.swing.JMenuItem jmi_gestion_notas;
    private javax.swing.JMenuItem jmi_listar_inscripciones;
    // End of variables declaration//GEN-END:variables

}
